"""Add new fields to models

Revision ID: dd45a51f93c5
Revises: 
Create Date: 2025-05-12 02:26:23.588106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd45a51f93c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('title', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('participants', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('bookings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('rooms', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('floor', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('rooms', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_admin')
    op.alter_column('rooms', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('rooms', 'created_at')
    op.drop_column('rooms', 'floor')
    op.drop_column('rooms', 'is_active')
    op.drop_column('bookings', 'created_at')
    op.drop_column('bookings', 'notes')
    op.drop_column('bookings', 'is_cancelled')
    op.drop_column('bookings', 'participants')
    op.drop_column('bookings', 'title')
    # ### end Alembic commands ###
